/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    media: Media;
    pages: Page;
    users: User;
    hotels: Hotel;
    fleets: Fleet;
    events: Event;
    tours: Tour;
    venues: Venue;
    event_bookings: EventBooking;
    event_booking_payments: EventBookingPayment;
    tour_bookings: TourBooking;
    tour_booking_payments: TourBookingPayment;
    'email-logs': EmailLog;
    trusted_partners: TrustedPartner;
    auto_login_sessions: AutoLoginSession;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    exports: Export;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    fleets: FleetsSelect<false> | FleetsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    event_bookings: EventBookingsSelect<false> | EventBookingsSelect<true>;
    event_booking_payments: EventBookingPaymentsSelect<false> | EventBookingPaymentsSelect<true>;
    tour_bookings: TourBookingsSelect<false> | TourBookingsSelect<true>;
    tour_booking_payments: TourBookingPaymentsSelect<false> | TourBookingPaymentsSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    trusted_partners: TrustedPartnersSelect<false> | TrustedPartnersSelect<true>;
    auto_login_sessions: AutoLoginSessionsSelect<false> | AutoLoginSessionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Name of the category
   */
  name: string;
  /**
   * Brief description of what this category represents
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'homeHero' | 'splitHeroWithCTA';
    title?: string | null;
    subtitle?: string | null;
    description?: string | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    missionTitle?: string | null;
    missionText?: string | null;
    missionImage?: (number | null) | Media;
    missionBackgroundColor?:
      | ('bg-beige' | 'bg-black' | 'bg-cream' | 'bg-gray' | 'bg-mustard' | 'bg-purple' | 'bg-rust' | 'bg-white')
      | null;
    button?: {
      text?: string | null;
      link?: string | null;
      variant?: ('default' | 'mustard' | 'link') | null;
      size?: ('default' | 'small' | 'large') | null;
      fullWidth?: boolean | null;
    };
    media?: (number | null) | Media;
    splitHero?: {
      heading?: string | null;
      mainTitle?: string | null;
      mainSubtitle?: string | null;
      mainDescription?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      contentPosition?: ('left' | 'right') | null;
      contentType?: ('card' | 'image' | 'none') | null;
      contentImage?: (number | null) | Media;
      useCardBlock?: boolean | null;
      cardBlock?: CardBlock[] | null;
    };
  };
  layout: (
    | BannerBlockConfig
    | CardBlock
    | ContentBlock
    | CallToActionBlock
    | CustomMediaBlockConfig
    | DescriptionBlockConfig
    | EventListConfig
    | FAQBlock
    | FeatureBlockConfig
    | FleetListConfig
    | FormBlock
    | HotelsBlockConfig
    | HotelServicingConfig
    | HTMLBlockConfig
    | InfoBlockConfig
    | LocalReviewsConfig
    | MediaBlock
    | NewsletterBlock
    | RatingBlock
    | RequestQuoteConfig
    | ShopperApprovedBlockConfig
    | TestimonialBlockConfig
    | ToursListConfig
    | TrustedPartnerConfig
    | VisualChecklistBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Toggle this to enable or disable SEO metadata for this page. When disabled, the page will not be indexed by search engines.
   */
  enableMetadata?: boolean | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock".
 */
export interface CardBlock {
  title: string;
  subtitle?: string | null;
  primaryText?: string | null;
  primaryTextColor?: ('text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust') | null;
  /**
   * Use [highlight] text [/highlight] syntax to highlight specific words or phrases
   */
  secondaryText?: string | null;
  secondaryTextColor?: ('text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust') | null;
  media?: (number | null) | Media;
  imagePosition?: ('left' | 'right') | null;
  button?: {
    text?: string | null;
    link?: string | null;
    variant?: ('default' | 'mustard' | 'link') | null;
    size?: ('default' | 'small' | 'large') | null;
    fullWidth?: boolean | null;
  };
  backgroundColor?: ('bg-white' | 'bg-mustard') | null;
  titleColor?: ('text-mustard' | 'text-gray') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlockConfig".
 */
export interface BannerBlockConfig {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bannerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomMediaBlockConfig".
 */
export interface CustomMediaBlockConfig {
  title?: string | null;
  subtitle?: string | null;
  mediaItems: {
    isEventItem?: boolean | null;
    isTourItem?: boolean | null;
    eventTitle?: string | null;
    eventDate?: string | null;
    eventPlace?: string | null;
    isTeamMember?: boolean | null;
    media: number | Media;
    /**
     * When set, clicking on this media item will navigate to this link.
     */
    d?: {
      link?: {
        type?: ('reference' | 'custom') | null;
        newTab?: boolean | null;
        reference?: {
          relationTo: 'pages';
          value: number | Page;
        } | null;
        url?: string | null;
      };
    };
    name?: string | null;
    position?: string | null;
    /**
     * This is the caption that will be displayed below the image.
     */
    caption?: string | null;
    /**
     * This is the text that will be displayed on bottom of the image.
     */
    overlayText?: string | null;
    bgColor?: ('bg-black' | 'bg-white' | 'bg-beige' | 'bg-mustard' | 'bg-gray' | 'bg-rust') | null;
    textColor?: ('text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust') | null;
    id?: string | null;
  }[];
  imageSpacing?: number | null;
  backgroundColor?:
    | ('bg-beige' | 'bg-white' | 'bg-gray' | 'bg-black' | 'bg-mustard' | 'bg-purple' | 'bg-rust' | 'bg-cream')
    | null;
  viewType: 'grid' | 'carousel';
  itemsPerRow: 'auto' | '1' | '2' | '3' | '4';
  buttonText?: string | null;
  buttonLink?: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
      label: string;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'customMediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DescriptionBlockConfig".
 */
export interface DescriptionBlockConfig {
  blockTitle?: string | null;
  heading?: string | null;
  headingTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  subheading?: string | null;
  subheadingTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  /**
   * You can use [highlight]text[/highlight] to highlight words, and [paragraph]...[/paragraph] to create multiple paragraphs. Example: [paragraph]First [highlight]highlighted[/highlight] paragraph.[/paragraph][paragraph]Second paragraph.[/paragraph]
   */
  quoteText?: string | null;
  quoteTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  showQuote?: boolean | null;
  hasButton?: boolean | null;
  button?: {
    text?: string | null;
    link?: string | null;
  };
  backgroundColor?: ('beige' | 'white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'descriptionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListConfig".
 */
export interface EventListConfig {
  title?: string | null;
  subtitle?: string | null;
  /**
   * If a category is selected, only events from this category will display.
   */
  category?: (number | null) | Category;
  /**
   * If events are selected, only these events will be displayed. Leave empty to show upcoming 8 events.
   */
  selectedEvents?: (number | Event)[] | null;
  backgroundColor?: ('bg-beige' | 'bg-white' | 'bg-gray' | 'bg-black') | null;
  viewType: 'grid' | 'carousel';
  itemsPerRow: 'auto' | '1' | '2' | '3' | '4';
  buttonText?: string | null;
  buttonLink?: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
      label: string;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  venue: number | Venue;
  description?: string | null;
  /**
   * Event duration in hours
   */
  duration_hours?: number | null;
  /**
   * Select a category for this event
   */
  category?: (number | null) | Category;
  status: 'active' | 'inactive' | 'cancelled';
  eventAvatarImage: number | Media;
  /**
   * Link to the event details page
   */
  eventDetailsPageLink?: {
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
    };
  };
  /**
   * Add multiple schedule dates with pickup details for this event
   */
  schedules?:
    | {
        /**
         * Date and time when this event is scheduled
         */
        event_date_time: string;
        event_date_time_tz: SupportedTimezones;
        schedule_status: 'scheduled' | 'confirmed' | 'cancelled' | 'completed';
        /**
         * Special instructions for this event date
         */
        schedule_notes?: string | null;
        /**
         * Add pickup details for different hotels for this specific schedule
         */
        pickups?:
          | {
              hotel: number | Hotel;
              /**
               * Multiple pickup times available for this hotel
               */
              pickup_times: {
                /**
                 * Time for pickup at this hotel
                 */
                time: string;
                time_tz: SupportedTimezones;
                id?: string | null;
              }[];
              /**
               * Price per rider for this pickup
               */
              adult_price: number;
              /**
               * Price per child for this pickup
               */
              children_price?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  eventImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  address: string;
  city?: string | null;
  /**
   * List available facilities (Parking, WiFi, etc.)
   */
  facilities?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: number;
  name: string;
  /**
   * Priority order for displaying hotels (1 = highest priority, 100 = lowest priority). Default is 50.
   */
  priority: number;
  description?: string | null;
  location: string;
  rating?: number | null;
  /**
   * After this date, tours can no longer be booked for this hotel pickup. Leave empty if partnership has no expiration.
   */
  partnerValidTill?: string | null;
  /**
   * Select an image as a logo for the Trusted Partner. This will be displayed on the Trusted Partner block. Pick something that represents the concept or purpose of the Partner.
   */
  images: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title: string;
  backgroundStyle?: ('light' | 'cream') | null;
  sideImage?: (number | null) | Media;
  imagePosition?: ('left' | 'right') | null;
  faqs?:
    | {
        question: string;
        /**
         * You can use [highlight]text[/highlight] to highlight words, [paragraph]...[/paragraph] to create multiple paragraphs, and [link:url]text[/link] to create links. Examples: [paragraph]First [highlight]highlighted[/highlight] paragraph.[/paragraph][paragraph]Second paragraph with a [link:https://example.com]link[/link].[/paragraph]
         */
        answer?: string | null;
        isOpen?: boolean | null;
        logos?:
          | {
              logo: number | Media;
              name?: string | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlockConfig".
 */
export interface FeatureBlockConfig {
  features?:
    | {
        heading?: string | null;
        subheading?: string | null;
        image?: (number | null) | Media;
        imagePosition?: ('right' | 'left') | null;
        hasButton?: boolean | null;
        button?: {
          text?: string | null;
          link?: string | null;
          newTab?: boolean | null;
        };
        backgroundColor?: ('bg-beige' | 'bg-white') | null;
        id?: string | null;
      }[]
    | null;
  backgroundColor?: ('bg-beige' | 'bg-white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FleetListConfig".
 */
export interface FleetListConfig {
  selectedFleets: (number | Fleet)[];
  title: string;
  description: string;
  limit?: number | null;
  ctaText: string;
  ctaUrl: string;
  backgroundColor: 'bg-white' | 'bg-gray-100' | 'bg-mustard';
  id?: string | null;
  blockName?: string | null;
  blockType: 'fleetList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleets".
 */
export interface Fleet {
  id: number;
  vehicleName: string;
  description?: string | null;
  image: number | Media;
  /**
   * Link to the fleet details page
   */
  fleetDetailsPageLink?: {
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelsBlockConfig".
 */
export interface HotelsBlockConfig {
  relationTo?: 'hotels' | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'hotels';
        value: number | Hotel;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hotelsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelServicingConfig".
 */
export interface HotelServicingConfig {
  heading?: string | null;
  headingTextColor:
    | 'text-white'
    | 'text-beige'
    | 'text-black'
    | 'text-mustard'
    | 'text-gray'
    | 'text-rust'
    | 'text-purple';
  subheading?: string | null;
  subheadingTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  /**
   * Put Empty to show all hotels. Choose specific hotels to display in the carousel. Only active hotels will be shown to visitors.
   */
  selectedHotels?: (number | Hotel)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hotelServicing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HTMLBlockConfig".
 */
export interface HTMLBlockConfig {
  /**
   * Enter raw HTML code that will be rendered directly on the page
   */
  htmlContent: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'htmlBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoBlockConfig".
 */
export interface InfoBlockConfig {
  heading?: string | null;
  headingTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  subheading?: string | null;
  subheadingTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  bodyText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Use [highlight] text [/highlight] syntax to highlight specific words or phrases
   */
  quoteText?: string | null;
  quoteTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  showQuote?: boolean | null;
  hasImage?: boolean | null;
  image?: (number | null) | Media;
  imagePosition?: ('right' | 'left') | null;
  caption?: string | null;
  hasButton?: boolean | null;
  button?: {
    text?: string | null;
    link?: string | null;
  };
  backgroundColor?: ('beige' | 'white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalReviewsConfig".
 */
export interface LocalReviewsConfig {
  /**
   * Enter the LocalReviews widget ID (e.g., 39235046-b56d-419d-b6b4-dd3d4b849984)
   */
  widgetId: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'localReviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  headline: string;
  buttonText: string;
  backgroundColor: 'bg-mustard' | 'bg-rust' | 'bg-gray';
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RatingBlock".
 */
export interface RatingBlock {
  /**
   * Primary message displayed in the Rating
   */
  mainText: string;
  /**
   * Optional secondary message displayed below the main text
   */
  secondaryText?: string | null;
  /**
   * Choose the background color for the Rating block
   */
  cardBackgroundColor: 'bg-black' | 'bg-beige' | 'bg-gray' | 'bg-rust';
  /**
   * Choose the text color for the Rating block
   */
  textColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  showRating?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ratingBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RequestQuoteConfig".
 */
export interface RequestQuoteConfig {
  /**
   * If enabled, users must be logged in to view the widget.
   */
  requireAuthentication?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'requestQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopperApprovedBlockConfig".
 */
export interface ShopperApprovedBlockConfig {
  /**
   * Automatically load the ShopperApproved script when the component mounts
   */
  autoLoad?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'shopperApprovedBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlockConfig".
 */
export interface TestimonialBlockConfig {
  heading?: string | null;
  headingTextColor:
    | 'text-white'
    | 'text-beige'
    | 'text-black'
    | 'text-mustard'
    | 'text-gray'
    | 'text-rust'
    | 'text-purple';
  subheading?: string | null;
  subheadingTextColor:
    | 'text-white'
    | 'text-beige'
    | 'text-black'
    | 'text-mustard'
    | 'text-gray'
    | 'text-rust'
    | 'text-purple';
  testimonials: {
    testimonialHeading?: string | null;
    testimonialName: string;
    testimonialPlace?: string | null;
    testimonialTime?: string | null;
    /**
     * Use [highlight]text[/highlight] to highlight words, and [paragraph]...[/paragraph] to create multiple paragraphs. Example: [paragraph]First [highlight]highlighted[/highlight] paragraph.[/paragraph][paragraph]Second paragraph.[/paragraph]
     */
    testimonialText: string;
    id?: string | null;
  }[];
  showQuote?: boolean | null;
  carouselOptions?: {
    showNavigation?: boolean | null;
    showDots?: boolean | null;
  };
  hasButton?: boolean | null;
  button?: {
    text?: string | null;
    link?: string | null;
  };
  backgroundColor?: ('bg-beige' | 'bg-white') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToursListConfig".
 */
export interface ToursListConfig {
  title?: string | null;
  subtitle?: string | null;
  backgroundColor?: ('bg-beige' | 'bg-white' | 'bg-gray' | 'bg-black') | null;
  viewType: 'grid' | 'carousel';
  itemsPerRow: 'auto' | '1' | '2' | '3' | '4';
  id?: string | null;
  blockName?: string | null;
  blockType: 'toursList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustedPartnerConfig".
 */
export interface TrustedPartnerConfig {
  heading?: string | null;
  headingTextColor:
    | 'text-white'
    | 'text-beige'
    | 'text-black'
    | 'text-mustard'
    | 'text-gray'
    | 'text-rust'
    | 'text-purple';
  subheading?: string | null;
  subheadingTextColor: 'text-white' | 'text-beige' | 'text-black' | 'text-mustard' | 'text-gray' | 'text-rust';
  /**
   * Put Empty to show all partners/services. Choose specific trusted partners/services to display in the carousel. Only active partners/services will be shown to visitors.
   */
  selectedPartners?: (number | TrustedPartner)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustedPartner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted_partners".
 */
export interface TrustedPartner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Optional link to partner website
   */
  website?: {
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
    };
  };
  /**
   * Uncheck to hide this partner from display
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisualChecklistBlock".
 */
export interface VisualChecklistBlock {
  heading: string;
  textColor: 'text-gray' | 'text-mustard' | 'text-rust' | 'text-black';
  image?: (number | null) | Media;
  /**
   * When checked, the image will be positioned absolutely over the content
   */
  isImageAbsolute?: boolean | null;
  /**
   * When checked, the image will be visible for mobile
   */
  isImageVisibleForMobile?: boolean | null;
  items: {
    text: string;
    icon?: (number | null) | Media;
    itemTextColor: 'text-gray' | 'text-mustard' | 'text-rust' | 'text-black';
    id?: string | null;
  }[];
  hasButton?: boolean | null;
  button?: {
    text?: string | null;
    link?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'vcBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Google account ID for OAuth users
   */
  googleId?: string | null;
  /**
   * Apple account ID for OAuth users
   */
  appleId?: string | null;
  /**
   * Profile image URL (usually from OAuth provider)
   */
  image?: string | null;
  role?: ('admin' | 'user') | null;
  phoneNumber?: string | null;
  receiveTexts?: boolean | null;
  /**
   * Stripe Customer ID
   */
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  name: string;
  /**
   * If enabled, you can manage Schedule & Pickups for this tour
   */
  isBookable?: boolean | null;
  /**
   * Short description for tour listings
   */
  shortDescription: string;
  /**
   * Brief description for tour listings
   */
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Tour duration in hours
   */
  duration_hours: number;
  /**
   * The date when this tour becomes available for booking (optional)
   */
  tour_start_date?: string | null;
  tourAvatarImage: number | Media;
  tourDetailsPageHeroImage: number | Media;
  /**
   * Link to the tour details page
   */
  tourDetailsPageLink?: {
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
    };
  };
  /**
   * What time does this tour start each day? (e.g., 9:00 AM)
   */
  tour_start_time?: string | null;
  /**
   * Configure when this tour runs using the visual interface below.
   */
  recurrence_rule?: string | null;
  /**
   * How many months in advance can customers book this tour?
   */
  booking_window_months?: number | null;
  /**
   * General notes about tour timing and availability
   */
  schedule_notes?: string | null;
  /**
   * Add pickup details for different hotels for this tour
   */
  pickups?:
    | {
        hotel: number | Hotel;
        /**
         * Pickup time for this hotel (e.g., "9:00 AM", "2:30 PM")
         */
        pickup_time: string;
        /**
         * Price per adult for this pickup
         */
        adult_price: number;
        /**
         * Price per child for this pickup
         */
        children_price?: number | null;
        id?: string | null;
      }[]
    | null;
  tourImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_bookings".
 */
export interface EventBooking {
  id: number;
  /**
   * Unique booking reference number (auto-generated if empty)
   */
  bookingReference: string;
  /**
   * Attendee user
   */
  user: number | User;
  /**
   * Event being booked (shows events from last 24 hours when creating/editing, all events when viewing list)
   */
  event: number | Event;
  /**
   * ID of the event schedule
   */
  scheduleId: string;
  /**
   * Number of riders
   */
  adultCount: number;
  /**
   * Number of children
   */
  childCount?: number | null;
  /**
   * Pickup details
   */
  pickupDetails: {
    /**
     * Pickup location ID
     */
    locationId: string;
    /**
     * Hotel ID
     */
    hotelId?: number | null;
    /**
     * Pickup time ID
     */
    selectedTimeId?: string | null;
  };
  /**
   * Pricing details
   */
  pricing: {
    /**
     * Price per rider (auto-calculated)
     */
    adultPrice: number;
    /**
     * Price per child (auto-calculated)
     */
    childrenPrice?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Total for riders (auto-calculated)
     */
    adultTotal: number;
    /**
     * Total for children (auto-calculated)
     */
    childTotal?: number | null;
    /**
     * Total amount (auto-calculated)
     */
    totalAmount: number;
  };
  /**
   * Booking creator (defaults to current user)
   */
  bookedBy?: (number | null) | User;
  /**
   * Check this to mark as confirmed and send confirmation email instead of payment request.
   */
  paymentCollected?: boolean | null;
  /**
   * Booking status
   */
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
  /**
   * Additional notes
   */
  notes?: string | null;
  /**
   * Shopper Approved follow-up
   */
  reviewFollowup?: {
    reviewId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_booking_payments".
 */
export interface EventBookingPayment {
  id: number;
  /**
   * Unique payment reference
   */
  paymentReference: string;
  /**
   * Associated booking
   */
  booking: (number | EventBooking)[];
  /**
   * Paying user
   */
  user?: (number | null) | User;
  /**
   * Payment status
   */
  paymentStatus: 'pending' | 'failed' | 'completed';
  /**
   * Payment amount
   */
  amount: number;
  currency: 'USD';
  /**
   * Payment method
   */
  paymentMethod: string;
  /**
   * Stripe payment details
   */
  stripeDetails?: {
    /**
     * Stripe Payment Intent ID
     */
    stripePaymentIntentId?: string | null;
    /**
     * Stripe Customer ID
     */
    stripeCustomerId?: string | null;
    /**
     * Payment method type
     */
    paymentMethodType?: string | null;
    /**
     * Receipt URL
     */
    receiptUrl?: string | null;
    /**
     * Additional payment metadata
     */
    metadata?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Payment date
   */
  paymentDate?: string | null;
  /**
   * Transaction ID
   */
  transactionId?: string | null;
  /**
   * Refund status
   */
  refundStatus?: ('not_refunded' | 'pending' | 'refunded' | 'failed') | null;
  /**
   * Amount refunded (can be partial)
   */
  refundedAmount?: number | null;
  /**
   * Stripe Refund ID
   */
  stripeRefundId?: string | null;
  /**
   * Refund receipt URL
   */
  refundReceiptUrl?: string | null;
  /**
   * Payment notes
   */
  notes?: string | null;
  /**
   * Other payment details
   */
  others?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour_bookings".
 */
export interface TourBooking {
  id: number;
  /**
   * Unique booking reference number
   */
  bookingReference: string;
  /**
   * Attendee user
   */
  user?: (number | null) | User;
  /**
   * Booking creator
   */
  bookedBy?: (number | null) | User;
  /**
   * Tour being booked
   */
  tour: number | Tour;
  /**
   * Date and time of the scheduled tour
   */
  scheduledDate: string;
  /**
   * Number of riders
   */
  adultCount: number;
  /**
   * Number of children
   */
  childCount?: number | null;
  /**
   * Pickup details
   */
  pickupDetails: {
    /**
     * Pickup location ID
     */
    locationId: string;
    /**
     * Hotel ID
     */
    hotelId: number;
    /**
     * Calculated pickup date and time
     */
    pickupDateTime: string;
    /**
     * Tour date and time
     */
    tourDateTime: string;
  };
  /**
   * Pricing details
   */
  pricing: {
    /**
     * Price per rider
     */
    adultPrice: number;
    /**
     * Price per child
     */
    childrenPrice: number;
    /**
     * Total for riders
     */
    adultTotal: number;
    /**
     * Total for children
     */
    childTotal: number;
    /**
     * Total amount
     */
    totalAmount: number;
    /**
     * Currency
     */
    currency?: string | null;
  };
  /**
   * Booking status
   */
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
  /**
   * Additional notes
   */
  notes?: string | null;
  /**
   * Shopper Approved follow-up
   */
  reviewFollowup?: {
    reviewId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour_booking_payments".
 */
export interface TourBookingPayment {
  id: number;
  /**
   * Unique payment reference
   */
  paymentReference: string;
  /**
   * Associated booking
   */
  booking: (number | TourBooking)[];
  /**
   * Paying user
   */
  user?: (number | null) | User;
  /**
   * Payment status
   */
  paymentStatus: 'pending' | 'failed' | 'completed';
  /**
   * Payment amount
   */
  amount: number;
  currency: 'USD';
  /**
   * Payment method
   */
  paymentMethod: string;
  /**
   * Stripe payment details
   */
  stripeDetails?: {
    /**
     * Stripe Payment Intent ID
     */
    stripePaymentIntentId?: string | null;
    /**
     * Stripe Customer ID
     */
    stripeCustomerId?: string | null;
    /**
     * Payment method type
     */
    paymentMethodType?: string | null;
    /**
     * Receipt URL
     */
    receiptUrl?: string | null;
    /**
     * Additional payment metadata
     */
    metadata?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Payment date
   */
  paymentDate?: string | null;
  /**
   * Transaction ID
   */
  transactionId?: string | null;
  /**
   * Refund status
   */
  refundStatus?: ('not_refunded' | 'pending' | 'refunded' | 'failed') | null;
  /**
   * Amount refunded (can be partial)
   */
  refundedAmount?: number | null;
  /**
   * Stripe Refund ID
   */
  stripeRefundId?: string | null;
  /**
   * Refund receipt URL
   */
  refundReceiptUrl?: string | null;
  /**
   * Payment notes
   */
  notes?: string | null;
  /**
   * Other payment details
   */
  others?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  /**
   * Email address the email was sent to
   */
  sentTo: string;
  /**
   * Email address the email was sent from
   */
  sentFrom?: string | null;
  subject: string;
  /**
   * Type of email sent
   */
  emailType:
    | 'tour_booking_confirmation'
    | 'resend_email'
    | 'event_booking_confirmation'
    | 'event_booking_cancellation'
    | 'tour_booking_cancellation'
    | 'event_refund'
    | 'tour_refund'
    | 'event_pending_payment'
    | 'tour_pending_payment'
    | 'password_reset'
    | 'user_registration'
    | 'payment_failed'
    | 'payment_succeeded'
    | 'test_email'
    | 'admin_copy'
    | 'other';
  /**
   * SendGrid template ID used (if dynamic template)
   */
  templateId?: string | null;
  /**
   * Data sent to the email template
   */
  templateData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'sent' | 'failed' | 'pending';
  /**
   * Error message if email failed to send
   */
  errorMessage?: string | null;
  sentAt?: string | null;
  /**
   * User this email was sent to (if registered user)
   */
  user?: (number | null) | User;
  /**
   * Related booking reference (if applicable)
   */
  bookingReference?: string | null;
  /**
   * Additional data related to the email
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One-time use tokens for secure auto-login functionality
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auto_login_sessions".
 */
export interface AutoLoginSession {
  id: number;
  /**
   * Unique session token for one-time use
   */
  sessionToken: string;
  /**
   * User this session belongs to
   */
  user: number | User;
  /**
   * Associated booking ID
   */
  booking: number;
  /**
   * Type of booking (event or tour)
   */
  bookingType: 'event' | 'tour';
  /**
   * Whether this token has been used (one-time use)
   */
  used: boolean;
  /**
   * Token expiration timestamp
   */
  expiresAt: string;
  /**
   * IP address that used this token
   */
  ipAddress?: string | null;
  /**
   * User agent that used this token
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage data exports - view, download, and create new exports. Files are stored in S3.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  sort?: string | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'hotels';
        value: number | Hotel;
      } | null)
    | ({
        relationTo: 'fleets';
        value: number | Fleet;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'event_bookings';
        value: number | EventBooking;
      } | null)
    | ({
        relationTo: 'event_booking_payments';
        value: number | EventBookingPayment;
      } | null)
    | ({
        relationTo: 'tour_bookings';
        value: number | TourBooking;
      } | null)
    | ({
        relationTo: 'tour_booking_payments';
        value: number | TourBookingPayment;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'trusted_partners';
        value: number | TrustedPartner;
      } | null)
    | ({
        relationTo: 'auto_login_sessions';
        value: number | AutoLoginSession;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        missionTitle?: T;
        missionText?: T;
        missionImage?: T;
        missionBackgroundColor?: T;
        button?:
          | T
          | {
              text?: T;
              link?: T;
              variant?: T;
              size?: T;
              fullWidth?: T;
            };
        media?: T;
        splitHero?:
          | T
          | {
              heading?: T;
              mainTitle?: T;
              mainSubtitle?: T;
              mainDescription?: T;
              contentPosition?: T;
              contentType?: T;
              contentImage?: T;
              useCardBlock?: T;
              cardBlock?:
                | T
                | {
                    cardBlock?: T | CardBlockSelect<T>;
                  };
            };
      };
  layout?:
    | T
    | {
        bannerBlock?: T | BannerBlockConfigSelect<T>;
        cardBlock?: T | CardBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        customMediaBlock?: T | CustomMediaBlockConfigSelect<T>;
        descriptionBlock?: T | DescriptionBlockConfigSelect<T>;
        eventList?: T | EventListConfigSelect<T>;
        faqBlock?: T | FAQBlockSelect<T>;
        featureBlock?: T | FeatureBlockConfigSelect<T>;
        fleetList?: T | FleetListConfigSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        hotelsBlock?: T | HotelsBlockConfigSelect<T>;
        hotelServicing?: T | HotelServicingConfigSelect<T>;
        htmlBlock?: T | HTMLBlockConfigSelect<T>;
        infoBlock?: T | InfoBlockConfigSelect<T>;
        localReviews?: T | LocalReviewsConfigSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        ratingBlock?: T | RatingBlockSelect<T>;
        requestQuote?: T | RequestQuoteConfigSelect<T>;
        shopperApprovedBlock?: T | ShopperApprovedBlockConfigSelect<T>;
        testimonialBlock?: T | TestimonialBlockConfigSelect<T>;
        toursList?: T | ToursListConfigSelect<T>;
        trustedPartner?: T | TrustedPartnerConfigSelect<T>;
        vcBlock?: T | VisualChecklistBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  enableMetadata?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock_select".
 */
export interface CardBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  primaryText?: T;
  primaryTextColor?: T;
  secondaryText?: T;
  secondaryTextColor?: T;
  media?: T;
  imagePosition?: T;
  button?:
    | T
    | {
        text?: T;
        link?: T;
        variant?: T;
        size?: T;
        fullWidth?: T;
      };
  backgroundColor?: T;
  titleColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlockConfig_select".
 */
export interface BannerBlockConfigSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomMediaBlockConfig_select".
 */
export interface CustomMediaBlockConfigSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  mediaItems?:
    | T
    | {
        isEventItem?: T;
        isTourItem?: T;
        eventTitle?: T;
        eventDate?: T;
        eventPlace?: T;
        isTeamMember?: T;
        media?: T;
        d?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
            };
        name?: T;
        position?: T;
        caption?: T;
        overlayText?: T;
        bgColor?: T;
        textColor?: T;
        id?: T;
      };
  imageSpacing?: T;
  backgroundColor?: T;
  viewType?: T;
  itemsPerRow?: T;
  buttonText?: T;
  buttonLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DescriptionBlockConfig_select".
 */
export interface DescriptionBlockConfigSelect<T extends boolean = true> {
  blockTitle?: T;
  heading?: T;
  headingTextColor?: T;
  subheading?: T;
  subheadingTextColor?: T;
  quoteText?: T;
  quoteTextColor?: T;
  showQuote?: T;
  hasButton?: T;
  button?:
    | T
    | {
        text?: T;
        link?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListConfig_select".
 */
export interface EventListConfigSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  category?: T;
  selectedEvents?: T;
  backgroundColor?: T;
  viewType?: T;
  itemsPerRow?: T;
  buttonText?: T;
  buttonLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  backgroundStyle?: T;
  sideImage?: T;
  imagePosition?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        isOpen?: T;
        logos?:
          | T
          | {
              logo?: T;
              name?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlockConfig_select".
 */
export interface FeatureBlockConfigSelect<T extends boolean = true> {
  features?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
        imagePosition?: T;
        hasButton?: T;
        button?:
          | T
          | {
              text?: T;
              link?: T;
              newTab?: T;
            };
        backgroundColor?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FleetListConfig_select".
 */
export interface FleetListConfigSelect<T extends boolean = true> {
  selectedFleets?: T;
  title?: T;
  description?: T;
  limit?: T;
  ctaText?: T;
  ctaUrl?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelsBlockConfig_select".
 */
export interface HotelsBlockConfigSelect<T extends boolean = true> {
  relationTo?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HotelServicingConfig_select".
 */
export interface HotelServicingConfigSelect<T extends boolean = true> {
  heading?: T;
  headingTextColor?: T;
  subheading?: T;
  subheadingTextColor?: T;
  selectedHotels?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HTMLBlockConfig_select".
 */
export interface HTMLBlockConfigSelect<T extends boolean = true> {
  htmlContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoBlockConfig_select".
 */
export interface InfoBlockConfigSelect<T extends boolean = true> {
  heading?: T;
  headingTextColor?: T;
  subheading?: T;
  subheadingTextColor?: T;
  bodyText?: T;
  quoteText?: T;
  quoteTextColor?: T;
  showQuote?: T;
  hasImage?: T;
  image?: T;
  imagePosition?: T;
  caption?: T;
  hasButton?: T;
  button?:
    | T
    | {
        text?: T;
        link?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalReviewsConfig_select".
 */
export interface LocalReviewsConfigSelect<T extends boolean = true> {
  widgetId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  headline?: T;
  buttonText?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RatingBlock_select".
 */
export interface RatingBlockSelect<T extends boolean = true> {
  mainText?: T;
  secondaryText?: T;
  cardBackgroundColor?: T;
  textColor?: T;
  showRating?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RequestQuoteConfig_select".
 */
export interface RequestQuoteConfigSelect<T extends boolean = true> {
  requireAuthentication?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopperApprovedBlockConfig_select".
 */
export interface ShopperApprovedBlockConfigSelect<T extends boolean = true> {
  autoLoad?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlockConfig_select".
 */
export interface TestimonialBlockConfigSelect<T extends boolean = true> {
  heading?: T;
  headingTextColor?: T;
  subheading?: T;
  subheadingTextColor?: T;
  testimonials?:
    | T
    | {
        testimonialHeading?: T;
        testimonialName?: T;
        testimonialPlace?: T;
        testimonialTime?: T;
        testimonialText?: T;
        id?: T;
      };
  showQuote?: T;
  carouselOptions?:
    | T
    | {
        showNavigation?: T;
        showDots?: T;
      };
  hasButton?: T;
  button?:
    | T
    | {
        text?: T;
        link?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToursListConfig_select".
 */
export interface ToursListConfigSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundColor?: T;
  viewType?: T;
  itemsPerRow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustedPartnerConfig_select".
 */
export interface TrustedPartnerConfigSelect<T extends boolean = true> {
  heading?: T;
  headingTextColor?: T;
  subheading?: T;
  subheadingTextColor?: T;
  selectedPartners?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisualChecklistBlock_select".
 */
export interface VisualChecklistBlockSelect<T extends boolean = true> {
  heading?: T;
  textColor?: T;
  image?: T;
  isImageAbsolute?: T;
  isImageVisibleForMobile?: T;
  items?:
    | T
    | {
        text?: T;
        icon?: T;
        itemTextColor?: T;
        id?: T;
      };
  hasButton?: T;
  button?:
    | T
    | {
        text?: T;
        link?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  googleId?: T;
  appleId?: T;
  image?: T;
  role?: T;
  phoneNumber?: T;
  receiveTexts?: T;
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  name?: T;
  priority?: T;
  description?: T;
  location?: T;
  rating?: T;
  partnerValidTill?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleets_select".
 */
export interface FleetsSelect<T extends boolean = true> {
  vehicleName?: T;
  description?: T;
  image?: T;
  fleetDetailsPageLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  venue?: T;
  description?: T;
  duration_hours?: T;
  category?: T;
  status?: T;
  eventAvatarImage?: T;
  eventDetailsPageLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
      };
  schedules?:
    | T
    | {
        event_date_time?: T;
        event_date_time_tz?: T;
        schedule_status?: T;
        schedule_notes?: T;
        pickups?:
          | T
          | {
              hotel?: T;
              pickup_times?:
                | T
                | {
                    time?: T;
                    time_tz?: T;
                    id?: T;
                  };
              adult_price?: T;
              children_price?: T;
              id?: T;
            };
        id?: T;
      };
  eventImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  name?: T;
  isBookable?: T;
  shortDescription?: T;
  description?: T;
  duration_hours?: T;
  tour_start_date?: T;
  tourAvatarImage?: T;
  tourDetailsPageHeroImage?: T;
  tourDetailsPageLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
      };
  tour_start_time?: T;
  recurrence_rule?: T;
  booking_window_months?: T;
  schedule_notes?: T;
  pickups?:
    | T
    | {
        hotel?: T;
        pickup_time?: T;
        adult_price?: T;
        children_price?: T;
        id?: T;
      };
  tourImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  facilities?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_bookings_select".
 */
export interface EventBookingsSelect<T extends boolean = true> {
  bookingReference?: T;
  user?: T;
  event?: T;
  scheduleId?: T;
  adultCount?: T;
  childCount?: T;
  pickupDetails?:
    | T
    | {
        locationId?: T;
        hotelId?: T;
        selectedTimeId?: T;
      };
  pricing?:
    | T
    | {
        adultPrice?: T;
        childrenPrice?: T;
        currency?: T;
        adultTotal?: T;
        childTotal?: T;
        totalAmount?: T;
      };
  bookedBy?: T;
  paymentCollected?: T;
  status?: T;
  notes?: T;
  reviewFollowup?:
    | T
    | {
        reviewId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_booking_payments_select".
 */
export interface EventBookingPaymentsSelect<T extends boolean = true> {
  paymentReference?: T;
  booking?: T;
  user?: T;
  paymentStatus?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  stripeDetails?:
    | T
    | {
        stripePaymentIntentId?: T;
        stripeCustomerId?: T;
        paymentMethodType?: T;
        receiptUrl?: T;
        metadata?: T;
      };
  paymentDate?: T;
  transactionId?: T;
  refundStatus?: T;
  refundedAmount?: T;
  stripeRefundId?: T;
  refundReceiptUrl?: T;
  notes?: T;
  others?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour_bookings_select".
 */
export interface TourBookingsSelect<T extends boolean = true> {
  bookingReference?: T;
  user?: T;
  bookedBy?: T;
  tour?: T;
  scheduledDate?: T;
  adultCount?: T;
  childCount?: T;
  pickupDetails?:
    | T
    | {
        locationId?: T;
        hotelId?: T;
        pickupDateTime?: T;
        tourDateTime?: T;
      };
  pricing?:
    | T
    | {
        adultPrice?: T;
        childrenPrice?: T;
        adultTotal?: T;
        childTotal?: T;
        totalAmount?: T;
        currency?: T;
      };
  status?: T;
  notes?: T;
  reviewFollowup?:
    | T
    | {
        reviewId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour_booking_payments_select".
 */
export interface TourBookingPaymentsSelect<T extends boolean = true> {
  paymentReference?: T;
  booking?: T;
  user?: T;
  paymentStatus?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  stripeDetails?:
    | T
    | {
        stripePaymentIntentId?: T;
        stripeCustomerId?: T;
        paymentMethodType?: T;
        receiptUrl?: T;
        metadata?: T;
      };
  paymentDate?: T;
  transactionId?: T;
  refundStatus?: T;
  refundedAmount?: T;
  stripeRefundId?: T;
  refundReceiptUrl?: T;
  notes?: T;
  others?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  sentTo?: T;
  sentFrom?: T;
  subject?: T;
  emailType?: T;
  templateId?: T;
  templateData?: T;
  status?: T;
  errorMessage?: T;
  sentAt?: T;
  user?: T;
  bookingReference?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted_partners_select".
 */
export interface TrustedPartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auto_login_sessions_select".
 */
export interface AutoLoginSessionsSelect<T extends boolean = true> {
  sessionToken?: T;
  user?: T;
  booking?: T;
  bookingType?: T;
  used?: T;
  expiresAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  sort?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        subItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: number | Media;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  faqLink: {
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
      label: string;
    };
  };
  socialLinks?:
    | {
        label?: string | null;
        newTab?: boolean | null;
        url?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  websiteCredit?: string | null;
  websiteCreditUrl?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        subItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  address?: T;
  phone?: T;
  email?: T;
  faqLink?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  socialLinks?:
    | T
    | {
        label?: T;
        newTab?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  websiteCredit?: T;
  websiteCreditUrl?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}